sonar.projectKey=Crinklyfoster_enterprise-rag-assistant
sonar.organization=crinklyfoster

sonar.sources=backend/app,frontend

sonar.exclusions=**/node_modules/**,**/.next/**,**/__pycache__/**

sonar.python.version=3.12