"""add chat session title

Revision ID: dd865ba3a5ac
Revises: 20260615_01
Create Date: 2026-06-15 12:09:21.236717
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd865ba3a5ac'
down_revision: Union[str, Sequence[str], None] = '20260615_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
